[project]
name = "safaz"
version = "0.1.0"
description = "SFZ import and export for uFor instruments"
readme = "README.md"
license = "MIT"
authors = [{ name = "Tom Ritchford", email = "tom@swirly.com" }]
requires-python = ">=3.13"
dependencies = ["ufor", "pydantic>=2.13.4", "soundfile"]

[project.urls]
Repository = "https://github.com/rec/safaz"

[dependency-groups]
dev = [
    "pytest",
    "pytest-regressions",
    "pytest-xdist>=3.8.0",
    "ruff",
    "ty",
    "pyupgrade",
]

reference = ["enge", "numpy", "mido"]

[tool.uv]
override-dependencies = ["ufor @ git+ssh://git@github.com/rec/ufor.git@e24e9aea1323c998c17f855f8ba5c776d8506da0"]

[tool.uv.sources]
enge = { git = "ssh://git@github.com/rec/enge.git", rev = "0292931487bcee6a7bae32f16e1f6b7712739b43" }
ufor = { git = "ssh://git@github.com/rec/ufor.git", rev = "e24e9aea1323c998c17f855f8ba5c776d8506da0" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "single"

[tool.pytest.ini_options]
testpaths = ["test"]
