[project]
name = "safaz"
version = "0.1.0"
description = "SFZ import and export for uFor instruments"
readme = "README.md"
license = "MIT"
authors = [{ name = "Tom Ritchford", email = "tom@swirly.com" }]
requires-python = ">=3.13"
classifiers = ["Programming Language :: Python :: 3.15"]
dependencies = ["ufor", "pydantic>=2.13.4", "soundfile"]

[project.urls]
Repository = "https://github.com/rec/safaz"

[dependency-groups]
dev = [
    "pytest",
    "pytest-regressions",
    "pytest-xdist>=3.8.0",
    "ruff",
    "ty",
    "pyupgrade",
]

reference = ["enge", "numpy", "mido"]

[tool.uv]
override-dependencies = ["ufor @ git+ssh://git@github.com/rec/ufor.git@5cea0275f1e3cac05540a1d6c8561063a2c94ab1"]

[tool.uv.sources]
enge = { git = "ssh://git@github.com/rec/enge.git", rev = "1bcb76566b813a1566afe0bdf1ed3092e40ed278" }
ufor = { git = "ssh://git@github.com/rec/ufor.git", rev = "5cea0275f1e3cac05540a1d6c8561063a2c94ab1" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "single"

[tool.pytest.ini_options]
testpaths = ["test"]
